### ISSUE TITLE
[ACTION] Add `benchmark_path` field to projects.json and pipeline

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#118]
Part of [Proposal-002 - Run the CNCF project benchmark tests as part of the automated pipeline
](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-002-run.md)

# Task Description

This issue tracks implementing part of proposal 2. So the existing pipeline is extended to call the benchmark workflow defined in the `projects.json` metadata file.

#121 is related to create the benchmark workflow for Falco

## Tasks

- [ ] Add a new `benchmark_path` field in [projects.json](https://github.com/cncf-tags/green-reviews-tooling/blob/main/projects/projects.json).
- [ ] Update the [benchmark pipeline](https://github.com/cncf-tags/green-reviews-tooling/blob/main/.github/workflows/benchmark-pipeline.yaml) workflow to take `benchmark_path` as an input and call the benchmark workflow using the `uses` syntax

**Comment by vallss** [comment]
I can work on this!

**Comment by vallss** [comment]
Hi @rossf7, do we have a value for the `benchmark_path` field inside the `project.json`? Or we leave it like this?
```
    "projects": [
        {
            "name": "falco",
            "organization": "falcosecurity",
            "benchmark_path": "",
            "configs": [
                "ebpf",
                "modern-ebpf",
                "kmod"
            ]
        }
    ]
```

**Comment by rossf7** [comment]
> do we have a value for the benchmark_path field inside the project.json? Or we leave it like this?

Hi @vallss not yet, let's leave it blank for now.

Once the workflow is added in #121 we can populate the JSON and integrate both changes.
