### ISSUE TITLE
[ACTION] Request new GitHub access tokens for green reviews

### ISSUE THREAD

**Issue by rossf7** [cncf-tags/green-reviews-tooling#140]
Follow up to #7 

Hi @RobertKielty for the green reviews project we're using 2 GitHub PATs that expire today. See https://github.com/cncf-tags/green-reviews-tooling/issues/7#issuecomment-2189406546

Could you generate new tokens for us and share with @leonardpahlke ?

The permissions needed are the same

Flux token

> Read access to metadata
> Read and Write access to administration and code

Pipeline token

> "Actions" repository permissions (write)

**Comment by RobertKielty** [comment]
I'll take a look!

**Comment by RobertKielty** [comment]
I've just updated the wg-green-review-benchmark-pipeline I have shared the PAT with @leonardpahlke and set the exipry date to be Wed 26th NOV 2025. 

It seems that the wg-green-review-flux has not been used within the past 5 months? Is this token still required? Check and let me know, either here or feel freee to reach out to me on Slack.

**Comment by rossf7** [comment]
Thank you @RobertKielty! 

> It seems that the wg-green-review-flux has not been used within the past 5 months? Is this token still required? 

As discussed in slack we are using flux but there are also no errors from source-controller. We'll investigate further and post updates here.
