### ISSUE TITLE
[ACTION] - Investigate why not all falco configurations are benchmarked

### ISSUE THREAD

**Issue by rossf7** [cncf-tags/green-reviews-tooling#142]
With latest fixes the benchmark pipeline is triggered for each of the 3 falco configurations.

However only 2/3 pipeline runs are successful. The 3rd fails with an error that looks related to GitHub Actions concurrency setting 
https://github.com/cncf-tags/green-reviews-tooling/blob/45185e85d0c8e7d8a06009b306d1421ace9c749a/.github/workflows/benchmark-pipeline.yaml#L29-L30

```
Benchmark Pipeline
Canceling since a higher priority waiting request for 'benchmark' exists
```

e.g. https://github.com/cncf-tags/green-reviews-tooling/actions/runs/12155458645

**Comment by SRF-Audio** [comment]
@rossf7 I can take a look at this one if you're ok with it.

**Comment by rossf7** [comment]
Thank you @SRF-Audio that would be great! I've assigned you.

Let me know if you need more information or I can help somehow.

**Comment by SRF-Audio** [comment]
Thanks @rossf7. 

Actually there is. As a repo admin, are you able to get me a HH:mm:ss timestamp for when each of these triggered, exactly?
- https://github.com/cncf-tags/green-reviews-tooling/actions/runs/12155458570 
- https://github.com/cncf-tags/green-reviews-tooling/actions/runs/12155458645
- https://github.com/cncf-tags/green-reviews-tooling/actions/runs/12155458674

When I look at the workflow runs over the past few days, it seems like each commit SHA is triggering 3x discrete instances of the benchmark pipeline. I'd like to verify that with a specific timestamp. 

I presume that the intent is that one commit SHA produces one pipeline instance?

**Comment by SRF-Audio** [comment]
So, we'd need to figure out why 3x trigger events happen from 1 commit SHA. 

The behavior seems to align with [the concurrency documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs), where only 1 active, and 1 pending job can be in the queue. 

If the intent *is* actually for 3 simultaneous pipelines from a single commit SHA, then I think we'd need to do something like:
```
concurrency:
  group: benchmark-${{ github.run_id }}
```

**Comment by rossf7** [comment]
> The behavior seems to align with [the concurrency documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs), where only 1 active, and 1 pending job can be in the queue.

Thanks @SRF-Audio yes this is indeed the issue. 

> We will use [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) to only allow a single execution of the pipeline at any one time. 

This is from [proposal 1](https://github.com/cncf-tags/green-reviews-tooling/blob/45185e85d0c8e7d8a06009b306d1421ace9c749a/docs/proposals/proposal-001-trigger-and-deploy.md#deploy) which links to the same docs! I think past me must have misread them :(

The reason we would like to run the pipelines sequentially is because we have a single node to do the benchmarking.

When we can provision nodes dynamically we could create a node per pipeline instance but we're not there yet. We would also need limits to not create an excessive number of nodes. 

Do you think using `cancel-in-progress: false` would let us execute the 3rd config successfully? 

If so I think this may be the best solution for now.

**Comment by SRF-Audio** [comment]
@rossf7 I have a branch ready to PR, but I think I need to be added to the repo:
```
git push --set-upstream origin issue-142
ERROR: Permission to cncf-tags/green-reviews-tooling.git denied to SRF-Audio.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
