### ISSUE TITLE
[Action] Create kubeconfig with read-only scope

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#18]
We need to give individual contributors read-only access to the cluster. 

This can be done by creating a Role with “get”, ”watch”, ”list” permissions, create a ServiceAccount, then generate a kubeconfig for this. 

The resources should be limited to Pods to begin with.

See [here](https://codeforphilly.github.io/chime/operations/limited-kubeconfigs/limited-kubeconfigs.html) for a tutorial/example of how to do this.

**Comment by dipankardas011** [comment]
### Questions
- Should this be automated process or done once manually?
- Also should we use clusterRole or namespaced scoped role?

**Comment by nikimanoledaki** [comment]
Wonderful, thank you @dipankardas011!

> Should this be automated process or done once manually?

We can start with one-time manually to unblock contributors. It would then be great if you could suggest a process to automate this as part of this issue as well since clusters will be ephemeral :)

> Also should we use clusterRole or namespaced scoped role?

I think it's ok to have a cluster-wide clusterRole as long as it's read/list/watch 👍

**Comment by dipankardas011** [comment]
Also @nikimanoledaki can I assume we have the kubeconfig in some file or as a string type in any programmnig language?
I was thinking of using golang to use the kubernetes-go client to create those

but first I will try it out via manual process
