### ISSUE TITLE
[Action] Set up access to the cluster through the K8s dashboard

### ISSUE THREAD

**Issue by AntonioDiTuri** [cncf-tags/green-reviews-tooling#19]
Depends on/blocked by #18 

The current monitoring deployments lacks a user-friendly graphical interface. 

This issue is about implementing a Kubernetes dashboard to simplify resource visualization and management.

Here there is [a guide](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/) on how to set up the k8s Dashboard.

It is not specified what permissions the service account because in the [user creation example](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md) the official dashboard repo provides an example using admin role which we don't want to use because it would lead to security issues. 

You can start from the one created [in this issue](https://github.com/cncf-tags/green-reviews-tooling/issues/18). 

If additional permissions are needed you can create a new role called user-dashboard.

**Comment by dipankardas011** [comment]
[Updates] #18 is merged!
@AntonioDiTuri

**Comment by nikimanoledaki** [comment]
We've opted for a public Grafana instance that can provision custom-made Grafana dashboards. I'm not sure that we need the k8s dashboard since it is a general solution that isn't tailored to our needs. WDYT @AntonioDiTuri?

**Comment by rossf7** [comment]
I think this is still useful to make contributing easier. The public Grafana + Flux manifests help but it can still be useful to be able to see the cluster state.

Could we keep this but defer it till after KubeCon?
