### ISSUE TITLE
[Action] Create 1Password team Green Reviews WG

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#37]
## Goals
- [ ] Store cluster secrets
- [ ] Store and share the cluster's kubeconfig. We can then share this with individual contributors. This will also help tracking who has access. The cluster may be ephemeral or re-created, which means we need to share the kubeconfig again and again with multiple contributors. Sharing the kubeconfig each time is a lot of extra work for our TL @rossf7.

**Comment by nikimanoledaki** [comment]
@leonardpahlke is it possible to do this through opening a servicedesk ticket? 1Password is listed in the [tools that are available for projects](https://github.com/cncf/servicedesk?tab=readme-ov-file#tools) 👀

**Comment by leonardpahlke** [comment]
sure, we also need to do this for the entire TAG.

**Comment by leonardpahlke** [comment]
Thanks for bringing this up again! 🙌

**Comment by AntonioDiTuri** [comment]
Hi @leonardpahlke is there an update on this?

**Comment by leonardpahlke** [comment]
Opened this issue to get us on 1Password open source https://github.com/cncf/tag-env-sustainability/issues/336

**Comment by nikimanoledaki** [comment]
Thank you @leonardpahlke ! 

Removing this from the KubeCon Europe '24 milestone since it isn't a blocker

**Comment by rossf7** [comment]
All secrets are added to 1Password. They have the prefix Green Reviews and the label wg-green-reviews
