### ISSUE TITLE
[Action/SCI] Metrics for Energy Consumption (E) for Falco

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#38]
### SCI = ([E](https://sci-guide.greensoftware.foundation/E) * [I](https://sci-guide.greensoftware.foundation/I)) + [M](https://sci-guide.greensoftware.foundation/M) per [R](https://sci-guide.greensoftware.foundation/R)

- SCI documentation about Energy Consumption [E](https://sci-guide.greensoftware.foundation/E)

### Acceptance Criteria
- Measure energy consumption through Kepler e.g. joule / Pod

**Comment by raymundovr** [comment]
I'd love to help with this one
