### ISSUE TITLE
[Action/SCI] Metrics for Emissions factor (I) for Falco

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#39]
### SCI = ([E](https://sci-guide.greensoftware.foundation/E) * [I](https://sci-guide.greensoftware.foundation/I)) + [M](https://sci-guide.greensoftware.foundation/M) per [R](https://sci-guide.greensoftware.foundation/R)

 Carbon emission intensity per geographical region.
 
 ### Acceptance Criteria
  - [x] Identify the electricity grid of the Equinix geo we are using
  - [x] Replace carbon coefficient in SCI dashboard with the Equinix-specific one
  - [x] Add Emissions (I) to docs

**Comment by raymundovr** [comment]
I'd love to help with this one :)

**Comment by rossf7** [comment]
Hi @nikimanoledaki @raymundovr,
for the dynamic emissions factor I'd like to suggest using the grid-intensity-go tool that @mrchrisadams and I maintain. https://github.com/thegreenwebfoundation/grid-intensity-go

It has a prometheus exporter that integrates with the Electricity Maps API free tier. It provides this carbon intensity metric we could use in the dashboard.

```
curl -s http://localhost:8000/metrics | grep grid_intensity_carbon_average
# HELP grid_intensity_carbon_average Average carbon intensity for the electricity grid in this location.
# TYPE grid_intensity_carbon_average gauge
grid_intensity_carbon_average{location="FR",node="kind-control-plane",provider="ElectricityMap",region="",units="gCO2e per kWh"} 39
```

We have a little bit of work to do as we need to push the container image and helm chart to a registry. We should be able to add that pretty quickly if we want to use grid-intensity-go for this. WDYT?

**Comment by rossf7** [comment]
@raymundovr My thinking was to use the IEA average carbon intensity figure for France. As I thought this was a common approach.

However looking at their site it looks more complex :( They have both paid and free datasets and I can't see a way to access the data. https://www.iea.org/data-and-statistics/data-product/emissions-factors-2022

In grid-intensity-go we embed a dataset from Ember Climate from 2021 as they publish data with a CC-BY-SA 4.0 license. https://ember-climate.org/ we could follow a similar approach.

@mrchrisadams it would be great to get your thoughts on this.

**Comment by mrchrisadams** [comment]
hi @rossf7, annual data, the easiet option I can think of might be to use the helpfully formatted data we have in CO2.js. I've linked to the json file below:

https://github.com/thegreenwebfoundation/co2.js/blob/main/data/output/average-intensities.json#L422-L427

These are updated every month on a cronjob from Ember, to reflect any changes to their methodology, and represent the most up-to-date, easy to use open data that I can find.

The changes are also checked by fershad Irani (@fershad) and myself to catch anything and query them upstream. You can see the most recent example below:

https://github.com/thegreenwebfoundation/co2.js/pull/190

**Comment by rossf7** [comment]
Thank you @mrchrisadams using the value you have in CO2.js makes sense to me but I will defer to @nikimanoledaki and @raymundovr as they are driving this one! 

I'm working on the embodied emissions factor for #40 using Boavizta's dataset.

**Comment by raymundovr** [comment]
Thank you @mrchrisadams and @rossf7 for the great resources, really appreciated!
Linking the script that generates the `json` for reference: https://github.com/thegreenwebfoundation/co2.js/blob/main/data/functions/generate_average_co2.js

It seems reasonable to me to set this value for France in the board, at least to start with. What do you think @nikimanoledaki ?

**Comment by nikimanoledaki** [comment]
Thank you @raymundovr @rossf7 @mrchrisadams :) 
(I) is in the dashboard + docs have been added. Marking as completed! 🎉
