### ISSUE TITLE
[ACTION] Organize better the design document

### ISSUE THREAD

**Issue by AntonioDiTuri** [cncf-tags/green-reviews-tooling#47]
A proposal for a better organization of the design document will follow shortly in the next days

**Comment by nikimanoledaki** [comment]
At this point, we should move as much info as possible to this repo and decommission the design doc. It is out of date and hard to maintain and this adds to confusion. But we still need a way to onboard people and have up-to-date documentation.

As you suggested, we can create new Google docs for ad hoc design documents in the future.
