### ISSUE TITLE
[Action] Bootstrap Grafana dashboard

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#51]
We need to bootstrap a Grafana dashboard from scratch that we will add panels to. 

We could follow the same steps as the Kepler dashboard:
- ConfigMap with json blob for Grafana dashboard
- Follow the same steps as how we deployed Kepler with Flux

Example: https://github.com/cncf-tags/green-reviews-tooling/blob/main/clusters/base/kepler-grafana.yaml

**Comment by asiwaju001** [comment]
taking a look at this

**Comment by leonardpahlke** [comment]
@rossf7 @nikimanoledaki did the status of this changed? I was under the impression we already deployed prometheus and the grafana dashboard and show kepler metrics.

**Comment by nikimanoledaki** [comment]
@asiwaju001 we created a Grafana dashboard by adding the SCI components one by one so this can be closed now. There are some other issues with the label `good first issue` in the repo if you wish to take on something else. Otherwise, let's chat again during the next meeting to see what you might find interesting :)
