### ISSUE TITLE
[Tracking/Request] Create GitHub PAT to use with Flux

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#7]
Unblocks https://github.com/cncf-tags/green-reviews-tooling/issues/5

We want to use Flux as part of our GitOps approach to deploying the applications in the cluster that we are setting up for the sustainability assessments.

We would like to request a GitHub PAT from the `cncf-tags` org, please 

The Flux docs specify the requirements for the GitHub PAT for an Organization [here](https://fluxcd.io/flux/installation/bootstrap/github/#github-organization) - the docs recommend creating a bot account:
> If you want to bootstrap Flux for a repository owned by an GitHub organization, it is recommended to create a dedicated user for Flux under your organization.

> Generate a GitHub PAT for the Flux user that can create repositories by checking all permissions under repo.

> If you want to use an existing repository, the Flux user must have admin permissions for that repository.

We can use a [fine-grained PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#fine-grained-personal-access-tokens) since they are more secure than classic PATs.

**Comment by RobertKielty** [comment]
Hi @nikimanoledaki and @leonardpahlke

I've created a fine-grained token, wg-green-review-flux that grants the following access to the cncf-tags/green-reviews-tooling repo:

**Repository permissions**
 * Read access to metadata
 * Read and Write access to administration and code
 
I've shared the token with @leonardpahlke

**Comment by leonardpahlke** [comment]
Thanks @RobertKielty !

**Comment by nikimanoledaki** [comment]
Thank you @RobertKielty! 

We'll be able to close this once we test the PAT as part of https://github.com/cncf-tags/green-reviews-tooling/issues/5 👍

**Comment by AntonioDiTuri** [comment]
I tested this and it works! I think we can close this issue! Thanks everybody

**Comment by nikimanoledaki** [comment]
Wonderful, thank you for testing, @AntonioDiTuri! 🎉

**Comment by rossf7** [comment]
Reopening as for #99 we have a new workflow that we'd like to trigger via the REST API using [workflow_dispatch](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event)

https://github.com/cncf-tags/green-reviews-tooling/blob/main/.github/workflows/benchmark-pipeline.yaml

For that we need a new fine grained token with the permissions below.

> "Actions" repository permissions (write)

@RobertKielty could you help us with this?

cc @leonardpahlke @nikimanoledaki @AntonioDiTuri

**Comment by RobertKielty** [comment]
Working on this now.

**Comment by rossf7** [comment]
Thank you @RobertKielty for the quick turnaround. Much appreciated!

**Comment by rossf7** [comment]
Token is added as a secret and being used successfully here 🎉 
https://github.com/cncf-tags/green-reviews-tooling/actions/runs/9681217682

I'll add a reminder for the token expiry
