### ISSUE TITLE
[Tracking/Request] Access AWS through CNCF credits

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#8]
Unblocks https://github.com/cncf-tags/green-reviews-tooling/issues/1

### What is needed?
We need to open a Servicedesk ticket to get access to AWS so that we can use the credits offered by AWS for the CNCF: https://github.com/cncf/servicedesk#how-can-i-use-the-computing-infrastructure-provided-by-the-cncf

### Why is it needed?
This will enable the Green Reviews WG to create an S3 bucket to store the OpenTofu state for the Equinix Metal infrastructure & k3s-created cluster.

See also:
- https://github.com/cncf-tags/green-reviews-tooling/pull/6
- [Design doc discussion](https://docs.google.com/document/d/19fzZW-IMv2kDNatKFHeHh7wqcEN0e2N60wzxvCGZd48/edit?disco=AAABAz7sG7M)

### Who can access this?
AWS access can be limited to the TAG ENV leads for now, which is what we are doing with the Equinix infrastructure as well.

**Comment by jeefy** [comment]
Ping @vielmetti -- does Equinix have an s3-compatible object storage offering that we can leverage here? It feels kinda weird and inefficient needing Provider A around to store state for Provider B.

**Comment by Callisto13** [comment]
Equinix does _technically_ have s3 object storage, but it is not part of or tied into Metal (you can't just click around in your customer console and "get" object storage in the same way you can through AWS and the like). The s3 storage from Equinix is part of managed services, meaning it is not built or provided by the company. In this case the provider is Netapp, and the managed service offered through Equinix is basically [StorageGrid](https://www.netapp.com/data-storage/storagegrid/). It is only available in the Netherlands, although I think another EU metro is going to be added "soon". The only way I can see to get it right now is via a sales call, and I believe Equinix will connect it all up with the customer's other services (like Equinix Fabric etc). I am not sure what the user experience is like, how the docs are, or what the cost would be (I am finding out these things), but my gut would say AWS would be an easier choice.

If you would like to stay within Metal, and don't mind the maintenance overhead, another option would be to deploy an extra Metal server which is optimised for storage (basically choose one with large disks) and run [MinIO](https://github.com/equinix/terraform-metal-distributed-minio/) on it.

@nikimanoledaki lmk if you need anything else 👍

**Comment by rossf7** [comment]
Thanks @Callisto13! Since the s3 storage is not part of Metal I also think AWS is going to be the easier choice.

Object storage is a better fit rather than a dedicated server because we just need to store the tofu state but we can't run it inside the cluster due to the usual chicken egg problem fun :)

**Comment by nikimanoledaki** [comment]
Thank you all for your valuable input! Access to AWS for S3 would be the simplest solution with the least amount of overhead, which would be best in our case given that this is a community-led project so time and effort are limited.

Unfortunately, object storage access currently blocks the cluster provisioning PR and the rest of the WG's pipeline implementation. 🙁 

@jeefy @vielmetti, we would appreciate your feedback and help with this! Thank you 😊

**Comment by vielmetti** [comment]
There are a couple of tools that provide S3 compatible object storage. One or more of them might be appropriate for your needs. @Callisto13 referenced Minio - but I guess what I'd like to know first is how much storage you need (megabytes, gigabytes, terabytes)?

I am OOO until 12/11 and I know @jeefy is away but we hopefully can make some progress.

**Comment by rossf7** [comment]
> but I guess what I'd like to know first is how much storage you need (megabytes, gigabytes, terabytes)?

@jeefy @vielmetti We only need a small amount of storage. Currently the tofu state file is 10kb in the S3 bucket I tested with. It might grow a bit but not above the megabytes range.

cc @nikimanoledaki

**Comment by vielmetti** [comment]
I reached out to the "OpenTofu Community" Slack to ask for someone there to weigh in on the backend configuration options question.

**Comment by rossf7** [comment]
Hi @vielmetti, thanks for reaching out to the OpenTofu Slack. I also joined there and good idea to see if there is another backend we can use.

**Comment by rossf7** [comment]
@vielmetti thanks again for reaching out in the OpenTofu Slack. The feedback was very helpful and we could use a cloud backend instead of S3. https://opentofu.org/docs/cli/cloud/settings

One of the Spacelift cofounders kindly offered we could use their service for free since we are a CNCF project. I'm going to try this out to see how it compares with using S3.

I've added an item to discuss this at the next WG meeting (Wed 13 November @ 17:00 CET).

**Comment by rossf7** [comment]
Hi @jeefy I investigated using Spacelift as an alternative and we discussed it during the WG meeting yesterday and with @vielmetti. We feel using an S3 bucket from AWS is a better solution.

We could use the Spacelift CLI to manage the state. However under the hood Spacelift uses an AWS S3 bucket and we would be adding a 3rd party service as a dependency for the WG.

With an AWS S3 bucket we can use the OpenTofu CLI directly. This aligns with the goal we have of using CNCF projects when possible for our stack.

cc @nikimanoledaki @leonardpahlke @AntonioDiTuri

**Comment by nikimanoledaki** [comment]
Thank you @rossf7 & @vielmetti for syncing and looking into this.

@jeefy we would really appreciate your help with unblocking this, please! Thank you.

**Comment by nikimanoledaki** [comment]
@leonardpahlke, hi! Could you report back with updates about the service desk ticket, please? Thank you for your help with unblock this :)

**Comment by jeefy** [comment]
I'm getting out of the way lol. @idvoretskyi Would you mind tackling setting this up? :)

**Comment by nikimanoledaki** [comment]
Thank you for looking into this @jeefy & @idvoretskyi! 🙌

**Comment by nikimanoledaki** [comment]
@idvoretskyi which next steps would you recommend? Should we open a Service Desk issue?

**Comment by jeefy** [comment]
Quick update, redirected this from @idvoretskyi to someone from LF IT to unblock the request, bucket should be created shortly. :) Thanks!

**Comment by ynwa99** [comment]
Hello @nikimanoledaki -- My name is Shah and I'm with LF IT. I created a bucket named `tag-environmental-sustainability` within the CNCF AWS account. By default the bucket blocks all public access. How would you like to best access the bucket? Are there any particular users or a group alias you want me to assign IAM permissions to for this bucket?

**Comment by leonardpahlke** [comment]
Thank you so much @jeefy and @ynwa99 ! Could we name the bucket `tag-env-green-reviews-open-tofu` to better capture the use case / purpose of the bucket.

**Comment by leonardpahlke** [comment]
@ynwa99 — regarding access @cncf-tags/tag-env-leads + @cncf-tags/tag-env-wg-green-reviews-leads is the group that _could_ have access. Not sure how you usually maintain this list. For this useccase it may be a bit overhead. And it may be just easier to create a one technical user with just CLI access to this one bucket which we can use in our gitops worflow.

**Comment by leonardpahlke** [comment]
Not really. We just need one user. This can be sort of a technical user. tag-environmental-sustainability-tech-user or similar & CLI creds.

**Comment by leonardpahlke** [comment]
I opened a service desk issue to get a 1Password account to store the credentials

**Comment by ynwa99** [comment]
Hi Leo, thanks for chatting with me on Slack a bit more about this request. I'm happy to say there is now an S3 bucket in the CNCF AWS account available for the TAG env sustainability team to use. The bucket name is `tag-env-green-reviews-open-tofu` 

How would you like me to share the access key credentials?

**Comment by leonardpahlke** [comment]
thanks! If thats ok, you can send me the creds via Slack DM. We will get a 1Password account for the TAG but that will likely take a bit. see https://github.com/cncf/tag-env-sustainability/issues/336

**Comment by rossf7** [comment]
We've switched to use the new S3 bucket for the cluster. Thanks all for the help with this!
