### ISSUE TITLE
[ACTION] Run

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#86]
Part 2/4 of https://github.com/cncf-tags/green-reviews-tooling/issues/83 to deliver the pipeline automation of the Green Review for Falco.

## Problem

Currently, we are using Flux to watch the upstream Falco repository and run the benchmark tests constantly. The first proposal is looking into how to split this up to only deploy the CNCF Project (e.g. Falco) when needed. This proposal aims to provide a solution for how to deploy the benchmark tests only when they are needed.

Benchmark test example: https://github.com/falcosecurity/cncf-green-review-testing/blob/main/kustomize/falco-driver/ebpf/stress-ng.yaml#L27-L32

## Action items
- Write a proposal that answers the following questions:
  - the actions to take after the trigger from Proposal 1 https://github.com/cncf-tags/green-reviews-tooling/issues/84
  - how to 1) fetch and 2) run the benchmark tests through GitHub Actions for a specific project e.g. Falco
  - where benchmark tests should be located e.g. as a library in the `green-reviews-tooling` repo or upstream in a separate CNCF Project such as https://github.com/falcosecurity/cncf-green-review-testing
- Communicate these changes to the Falco team to change the benchmark test to a GitHub Action file

**Comment by leonardpahlke** [comment]
Could we add some details on this issue - the title and description don't tell us what it's about.

**Comment by locomundo** [comment]
Working on this!
