### ISSUE TITLE
[DOCUMENTATION] DNS record and Netlify deployment for the documentation website

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf-tags/green-reviews-tooling#91]
Now that the code for documentation website is merged to https://github.com/cncf-tags/green-reviews-tooling/tree/main/website we need to make it publicly available by setting up deployment in Netlify and getting DNS record created.

@leonardpahlke created a service desk ticket for CNCF to get this sorted out.

**Comment by nikimanoledaki** [comment]
Closing this given the decision to merge the Green Reviews WG docs under the TAG ENV website
